---
title: "ML2"
author: "Carla"
date: "2024-04-08"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

library(phyloseq)
library(mlr3)
library(mlr3learners)
library(mlr3filters)
library(mlr3tuning)
library(mlr3pipelines)
library(ranger)
library(caret)
library(dplyr)
library(ggplot2)

set.seed(1234)
```

# Experimento 2 - Leave cohort out variable Status (CRC/Control)

```{r include=TRUE}
# projects_filt <- c("PRJEB33634_B1", "Zackular")
# physeq_pre_filt <- subset_samples(physeq_pre_clr, !(sample_data(physeq_pre_clr)$project %in% projects_filt))

# PRE MOBER
physeq_pre <- physeq_pre_alr

otu_table_pre <- t(otu_table(physeq_pre, taxa_are_rows = TRUE))
otu_table_pre <- as.matrix(otu_table_pre)
status_pre <- sample_data(physeq_pre)$status
project_pre <- sample_data(physeq_pre)$project

data_ml_pre <- cbind(otu_table_pre, status_pre, project_pre)
data_ml_pre <- as.data.frame(data_ml_pre)

data_ml_pre$status_pre <- as.factor(data_ml_pre$status_pre)
data_ml_pre$project_pre <- as.factor(data_ml_pre$project_pre)

for (col in names(data_ml_pre)) {
  if (is.character(data_ml_pre[[col]]) || is.factor(data_ml_pre[[col]])) {
    data_ml_pre[[col]] <- as.numeric(data_ml_pre[[col]])
  }
}

data_ml_pre$status_pre <- as.factor(data_ml_pre$status_pre)
data_ml_pre$project_pre <- as.numeric(data_ml_pre$project_pre)

# POST MOBER
physeq_post <- physeq_output_alr

otu_table_post <- otu_table(physeq_post)
otu_table_post <- as.matrix(otu_table_post)
status_post <- sample_data(physeq_post)$status
project_post <- sample_data(physeq_post)$project

data_ml_post <- cbind(otu_table_post, status_post, project_post)
data_ml_post <- as.data.frame(data_ml_post)

data_ml_post$status_post <- as.factor(data_ml_post$status_post)
data_ml_post$project_post <- as.factor(data_ml_post$project_post)

for (col in names(data_ml_post)) {
  if (is.character(data_ml_post[[col]]) || is.factor(data_ml_post[[col]])) {
    data_ml_post[[col]] <- as.numeric(data_ml_post[[col]])
  }
}

data_ml_post$status_post <- as.factor(data_ml_post$status_post)
data_ml_post$project_post <- as.numeric(data_ml_post$project_post)
```

```{r include=TRUE}

run_ml_pipeline <- function(data_ml_pre, data_ml_post, model) {
  
  # Definir las particiones basadas en la columna 'project'
  f_pre <- as.factor(data_ml_pre$project_pre)
  f_post <- as.factor(data_ml_post$project_post)
  
  # Eliminar la columna project para que ni la uitilice como variable predictora
  data_ml_pre <- data_ml_pre %>% dplyr::select(-project_pre)
  data_ml_post <- data_ml_post %>% dplyr::select(-project_post)

  # Definición tasks
  if (model == "svm") {
    task_pre <- TaskClassif$new(id = "ml2_svm", backend = data_ml_pre, target = "status_pre")
    task_post <- TaskClassif$new(id = "ml2_svm_post", backend = data_ml_post, target = "status_post")
  } else if (model == "rf") {
    task_pre <- TaskClassif$new(id = "ml2_rf", backend = data_ml_pre, target = "status_pre")
    task_post <- TaskClassif$new(id = "ml2_rf_post", backend = data_ml_post, target = "status_post")
  } else if (model == "glmn") {
    task_pre <- TaskClassif$new(id = "ml2_glmn", backend = data_ml_pre, target = "status_pre")
    task_post <- TaskClassif$new(id = "ml2_glmn_post", backend = data_ml_post, target = "status_post")
  }
  
  # Modelo de aprendizaje automático
  if (model == "svm") {
    gr = po("filter", filter = flt("kruskal_test"), filter.frac = 0.03) %>>% po("learner", lrn("classif.svm"))
    learner = GraphLearner$new(gr)
  } else if (model == "rf") {
    gr = po("filter", filter = flt("kruskal_test"), filter.frac = 0.03) %>>% po("learner", lrn("classif.ranger"))
    learner = GraphLearner$new(gr)
  } else if (model == "glmn") {
    gr = po("filter", filter = flt("kruskal_test"), filter.frac = 0.03) %>>% po("learner", lrn("classif.glmnet"))
    learner = GraphLearner$new(gr)
  }
  
  # Crear el objeto de validación cruzada personalizada
  custom_cv_pre <- rsmp("custom_cv")
  custom_cv_post <- rsmp("custom_cv")
  
  # Instanciar la validación cruzada personalizada
  custom_cv_pre$instantiate(task_pre, f = f_pre)
  custom_cv_post$instantiate(task_post, f = f_post)
  
  # Proceso de evaluación
  eval_pre <- mlr3::resample(task = task_pre, learner = learner, resampling = custom_cv_pre)
  eval_post <- mlr3::resample(task = task_post, learner = learner, resampling = custom_cv_post)
  
  # Obtención métricas
  result_ce_pre <- eval_pre$aggregate(msr("classif.ce"))
  result_bacc_pre <- eval_pre$aggregate(msr("classif.bacc"))
  
  result_ce_post <- eval_post$aggregate(msr("classif.ce"))
  result_bacc_post <- eval_post$aggregate(msr("classif.bacc"))
  
  # Añadir de vuelta las columnas project para los resultados por cohorte
  data_ml_pre$project <- project_pre
  data_ml_post$project <- project_post
  
  # Resultados por cohorte
  results_per_cohort_pre <- lapply(unique(data_ml_pre$project), function(cohort) {
    cohort_idx <- which(data_ml_pre$project == cohort)
    cohort_preds <- eval_pre$prediction()$filter(row_ids = cohort_idx)
    list(
      cohort = cohort,
      ce = cohort_preds$score(msr("classif.ce")),
      bacc = cohort_preds$score(msr("classif.bacc"))
    )
  })
  
  results_per_cohort_post <- lapply(unique(data_ml_post$project), function(cohort) {
    cohort_idx <- which(data_ml_post$project == cohort)
    cohort_preds <- eval_post$prediction()$filter(row_ids = cohort_idx)
    list(
      cohort = cohort,
      ce = cohort_preds$score(msr("classif.ce")),
      bacc = cohort_preds$score(msr("classif.bacc"))
    )
  })
  
    return(list(
     overall = list(
       pre = list(ce = result_ce_pre, bacc = result_bacc_pre),
       post = list(ce = result_ce_post, bacc = result_bacc_post)
     ),
     per_cohort = list(
       pre = results_per_cohort_pre,
       post = results_per_cohort_post
     )
   ))
  
}

results_svm <- run_ml_pipeline(data_ml_pre, data_ml_post, "svm")
results_rf <- run_ml_pipeline(data_ml_pre, data_ml_post, "rf")
results_glmn <- run_ml_pipeline(data_ml_pre, data_ml_post, "glmn")
```

```{r include=TRUE}
# Resultados globales
format_resultados_globales <- function(results, model_name) {
  data.frame(
    Modelo = c(paste(model_name, "PRE", sep = "_"), paste(model_name, "POST", sep = "_")),
    Error = c(results$overall$pre$ce, results$overall$post$ce),
    Precision = c(results$overall$pre$bacc, results$overall$post$bacc)
  )
}

# Resultados por cohorte
format_resultados_cohorte <- function(results, model_name) {
  cohorts_pre <- do.call(rbind, lapply(results$per_cohort$pre, function(cohort_result) {
    data.frame(
      Cohort = cohort_result$cohort,
      Modelo = model_name,
      Modelo_fase = paste(model_name, "PRE", sep = "_"),
      Error = cohort_result$ce,
      Precision = cohort_result$bacc
    )
  }))
  
  cohorts_post <- do.call(rbind, lapply(results$per_cohort$post, function(cohort_result) {
    data.frame(
      Cohort = cohort_result$cohort,
      Modelo = model_name,
      Modelo_fase = paste(model_name, "POST", sep = "_"),
      Error = cohort_result$ce,
      Precision = cohort_result$bacc
    )
  }))
  
  cohorts <- rbind(cohorts_pre, cohorts_post)
  cohorts <- cohorts[order(cohorts$Cohort), ]
  
  return(cohorts)
}

# Formatear los resultados globales de cada modelo
resultados_global_svm <- format_resultados_globales(results_svm, "SVM")
resultados_global_rf <- format_resultados_globales(results_rf, "RandomForest")
resultados_global_glmn <- format_resultados_globales(results_glmn, "GLMNet")

# Formatear los resultados por cohortes de cada modelo
resultados_cohorte_svm <- format_resultados_cohorte(results_svm, "SVM")
resultados_cohorte_rf <- format_resultados_cohorte(results_rf, "RandomForest")
resultados_cohorte_glmn <- format_resultados_cohorte(results_glmn, "GLMNet")

resultados_global <- rbind(resultados_global_svm, resultados_global_rf, resultados_global_glmn)
resultados_cohorte <- rbind(resultados_cohorte_svm, resultados_cohorte_rf, resultados_cohorte_glmn)

resultados_global
resultados_cohorte
```

```{r include=TRUE}
# Plots
resultados_cohorte <- as.data.frame(resultados_cohorte)
resultados_cohorte$Phase <- ifelse(grepl("PRE", resultados_cohorte$Modelo_fase), "PRE", "POST")

resultados_cohorte_largos <- resultados_cohorte %>%
  pivot_longer(cols = c(Error, Precision), names_to = "Metric", values_to = "Value")

# Gráfico de Puntos de Error por Cohorte y Modelo
ggplot(resultados_cohorte_largos %>% filter(Metric == "Error"), aes(x = Cohort, y = Value, color = Modelo, shape = Modelo)) +
  geom_point(size = 3, position = position_dodge(width = 0.5)) +
  geom_errorbar(aes(ymin = Value - sd(Value), ymax = Value + sd(Value)), width = 0.2, position = position_dodge(width = 0.5)) +  
  facet_wrap(~ factor(Phase, levels = c("PRE", "POST")), scales = "free_y") +
  labs(title = "Error por Cohorte y Modelo",
       x = "Cohorte", y = "Error", color = "Modelo", shape = "Modelo") +  
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  ylim(0, 0.7)

# Gráfico de Puntos de Precisión por Cohorte y Modelo
ggplot(resultados_cohorte_largos %>% filter(Metric == "Precision"), aes(x = Cohort, y = Value, color = Modelo, shape = Modelo)) +
  geom_point(size = 3, position = position_dodge(width = 0.5)) +
  geom_errorbar(aes(ymin = Value - sd(Value), ymax = Value + sd(Value)), width = 0.2, position = position_dodge(width = 0.5)) +  
  facet_wrap(~ factor(Phase, levels = c("PRE", "POST")), scales = "free_y") +
  labs(title = "Precisión por Cohorte y Modelo",
       x = "Cohorte", y = "Precision", color = "Modelo", shape = "Modelo") +  
  theme_minimal() +
  theme(axis.text.x = element_text(angle = 45, hjust = 1)) +
  ylim(0.5, 1)


```