---
title: "Pca_post_clr"
author: "Carla"
date: "2024-02-13"
output: html_document
---

```{r include=TRUE}
# Instalar y cargar los paquetes necesarios si aún no lo has hecho
library(phyloseq)
library(dplyr)
library(tidyr)
```

Creamos el objeto phyloseq con el que crearemos la PCA a partir del output .h5ad que genera hacer proyección con MOBER 

```{r include=TRUE}
# Especifica la ruta al directorio que contiene los archivos CSV
csv_directory <- "C:/Users/Carla/Desktop/4o/Q1/TFG/samples/output/"

otu_file_clr <- list.files(path = csv_directory, pattern = "otu_table_clr.csv", full.names = TRUE)
sample_file_clr <- list.files(path = csv_directory, pattern = "sample_data_clr.csv", full.names = TRUE)

otu_clr <- read.csv(otu_file_clr, row.names = 1)
sample_data_clr <- read.csv(sample_file_clr, row.names = 1)

otu_table_clr <- otu_table(otu_clr, taxa_are_rows = TRUE)
otu_table_clr <- t(otu_table_clr)
sample_data_clr <- sample_data(sample_data_clr)

# Crear objeto phyloseq
physeq_output_clr <- phyloseq(otu_table_clr, sample_data_clr)
```

Representamos PCA

```{r include=TRUE}
otu_table_o <- otu_table(physeq_output_clr)
otu_post_clr <- t(otu_table(physeq_output_clr))
otu_post_clr <- as.matrix(otu_post_clr)

metadata_output_clr <- sample_data(physeq_output_clr)
meta_out_clr <- as.matrix(metadata_output_clr)
meta_out_clr <- as.data.frame(meta_out_clr)

cols <- c("status", "target_region")
meta_out_clr[,cols] <- lapply(meta_out_clr[,cols], as.factor)

pca_post_clr <- pca(X = otu_post_clr, ncomp = 2)
plot_pca_post_clr <- PLSDAbatch::Scatter_Density(object = pca_post_clr,
                                               batch = meta_out_clr[,"project"],
                                               trt = meta_out_clr[,"status"],
                                               batch.legend.title = 'Project',
                                               trt.legend.title = 'Status',
                                               title = 'With correction',
                                               xlim = c(-20,20), 
                                               ylim = c(-20, 20))
```