---
title: "Projection"
author: "Carla"
date: "2024-02-13"
output: html_document
---

```{r include=TRUE}
# Instalar y cargar los paquetes necesarios si aún no lo has hecho
library(phyloseq)
library(dplyr)
library(tidyr)

set.seed(1234)
```

Creamos el objeto phyloseq sobre el que calcularemos el PCA a partir del output .h5ad que genera hacer proyección con MOBER 

```{r include=TRUE}
# Especifica la ruta al directorio que contiene los archivos CSV
csv_directory <- "C:/Users/Carla/Desktop/4o/Q1/TFG/samples/output/"

otu_file <- list.files(path = csv_directory, pattern = "otu_table_abr.csv", full.names = TRUE)
sample_file <- list.files(path = csv_directory, pattern = "sample_data_abr.csv", full.names = TRUE)

otu <- read.csv(otu_file, row.names = 1)
sample_data <- read.csv(sample_file, row.names = 1)

otu_table <- otu_table(otu, taxa_are_rows = FALSE)
sample_data <- sample_data(sample_data)

# Crear objeto phyloseq
physeq_output_abr <- phyloseq(otu_table, sample_data)
physeq_output_abr
```

Representamos PCAs

Sin normalización

```{r include=TRUE}
otu_table_o <- otu_table(physeq_output)
otu_post <- as.matrix(otu_table_o)

metadata_output <- sample_data(physeq_output)
meta_post <- as.matrix(metadata_output)
meta_post <- as.data.frame(meta_post)

pca_post <- pca(X = otu_post, ncomp = 2)
plot_pca_post <- PLSDAbatch::Scatter_Density(object = pca_post,
                                               batch = meta_post[,"project"],
                                               trt = meta_post[,"status"],
                                               batch.legend.title = 'Project',
                                               trt.legend.title = 'Status',
                                               title = 'Con corrección',
                                               xlim = c(-3000, 1000), 
                                               ylim = c(-1250, 500))
```

CLR 

```{r include=TRUE}
otu_table_o <- otu_table(physeq_output_clr)
otu_post_clr <- otu_table(physeq_output_clr)
otu_post_clr <- as.matrix(otu_post_clr)

metadata_output_clr <- sample_data(physeq_output_clr)
meta_out_clr <- as.matrix(metadata_output_clr)
meta_out_clr <- as.data.frame(meta_out_clr)

cols <- c("project", "status")
meta_out_clr[,cols] <- lapply(meta_out_clr[,cols], as.factor)

pca_post_clr <- pca(X = otu_post_clr, ncomp = 2)
plot_pca_post_clr <- PLSDAbatch::Scatter_Density(object = pca_post_clr,
                                               batch = meta_out_clr[,"project"],
                                               trt = meta_out_clr[,"status"],
                                               batch.legend.title = 'Project',
                                               trt.legend.title = 'Status',
                                               title = 'Con corrección',
                                               xlim = c(-10, 10), 
                                               ylim = c(-10, 10))
```

ALR 

```{r include=TRUE}
otu_table_o <- otu_table(physeq_output_alr)
otu_post_alr <- otu_table(physeq_output_alr)
otu_post_alr <- as.matrix(otu_post_alr)

metadata_output_alr <- sample_data(physeq_output_alr)
meta_out_alr <- as.matrix(metadata_output_alr)
meta_out_alr <- as.data.frame(meta_out_alr)

cols <- c("project", "status")
meta_out_alr[,cols] <- lapply(meta_out_alr[,cols], as.factor)

pca_post_alr <- pca(X = otu_post_alr, ncomp = 2)
plot_pca_post_alr <- PLSDAbatch::Scatter_Density(object = pca_post_alr,
                                               batch = meta_out_alr[,"project"],
                                               trt = meta_out_alr[,"status"],
                                               batch.legend.title = 'Project',
                                               trt.legend.title = 'Status',
                                               title = 'Con corrección',
                                               xlim = c(-12, 12), 
                                               ylim = c(-12, 12))
```

Abundancias relativas 

```{r include=TRUE}
otu_table_o <- otu_table(physeq_output_abr)
otu_post_abr <- otu_table(physeq_output_abr)
otu_post_abr <- as.matrix(otu_post_abr)

metadata_output_abr <- sample_data(physeq_output_abr)
meta_out_abr <- as.matrix(metadata_output_abr)
meta_out_abr <- as.data.frame(meta_out_abr)

cols <- c("project", "status")
meta_out_abr[,cols] <- lapply(meta_out_abr[,cols], as.factor)

pca_post_abr <- pca(X = otu_post_abr, ncomp = 2)
plot_pca_post_abr <- PLSDAbatch::Scatter_Density(object = pca_post_abr,
                                               batch = meta_out_abr[,"project"],
                                               trt = meta_out_abr[,"status"],
                                               batch.legend.title = 'Project',
                                               trt.legend.title = 'Status',
                                               title = 'Con corrección',
                                               xlim = c(-3000, 1000), 
                                               ylim = c(-1250, 500))
```