---
title: "PCA"
author: "Carla"
date: "2024-02-02"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
if (!require("BiocManager", quietly = TRUE))
    install.packages("BiocManager")

BiocManager::install("mixOmics")

library(phyloseq)
library(vegan)
library(PCAtools)
library(openxlsx)
library(mixOmics)
```

Convertimos la lista de objetos phyloseq en un sólo objeto 

```{r include=TRUE}
physeq_agl_combined <- do.call("merge_phyloseq", physeq_agl_list_filtrado)
physeq_agl_combined
```

Representamos la PCA 

```{r include=TRUE}
otu_table <- otu_table(physeq_agl_combined)
otu <- t(otu_table)

write.xlsx(otu_table, file = "C:/Users/Carla/Desktop/4o/Q1/TFG/def_otu2.xlsx")

col<-rownames(otu)
row<-colnames(otu)

datos <- read_xlsx("C:/Users/Carla/Desktop/4o/Q1/TFG/def_otu2.xlsx", col_names = FALSE)

colnames(datos) <- col
rownames(datos) <- row

metadata <- sample_data(physeq_agl_combined)
metadata
metadata$Group <- ifelse(metadata$Group == 'Control', 'Control', 'CRC')


# CLR
datos_pseudo <- otu + 1
datos.clr <- logratio.transfo(as.matrix(datos_pseudo), 
                             logratio = 'CLR', offset = 0) 
pca.clr <- mixOmics::pca(otu)
plotIndiv(pca.clr, xlim = c(-180000,180000), ylim = c(-100000,100000))

pca.clr <- mixOmics::pca(datos.clr)
plotIndiv(pca.clr, xlim = c(-40,40), ylim = c(-50,50))

# Plot 
p_input <- PCAtools::pca(datos.clr, metadata = metadata, removeVar = 0.1)

biplot(p_input, xlim = c(-180000,180000), ylim = c(-100000,100000))

physeq_transf <- phyloseq::phyloseq(otu_table(datos.clr), 
                                    sample_data(physeq_agl_combined),
                                    tax_table(physeq_agl_combined))
```
