---
title: "PCA"
author: "Carla"
date: "2024-02-02"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
if (!require("BiocManager", quietly = TRUE))
    install.packages("BiocManager")

library(phyloseq)
library(vegan)
library(PCAtools)

library(PLSDAbatch) # gráficos PCA 
library(mixOmics) # normalización CLR 
library(compositions) # normalización ALR
library(ampvis2) # normalización abundancias relativas 

set.seed(1234)
```

Convertimos la lista de objetos phyloseq en un sólo objeto 

```{r include=TRUE}
tax_tables <- lapply(physeq_agl_list_filtrado, tax_table)
unified_taxa <- Reduce(function(x, y) unique(rbind(x, y)), tax_tables)

for (i in 1:length(physeq_agl_list_filtrado)) {
  tax_table(physeq_agl_list_filtrado[[i]]) <- unified_taxa
}

physeq_agl_combined_t <- do.call("merge_phyloseq", physeq_agl_list_filtrado)
physeq_agl_combined_t

physeq_agl_combined_t <- subset_samples(physeq_agl_combined_t, sample_data(physeq_agl_combined_t)$status != "adenoma")

projects_filt <- c("PRJEB33634_B1", "Zackular")
physeq_agl_combined_filt <- subset_samples(physeq_agl_combined_t, !(sample_data(physeq_agl_combined_t)$project %in% projects_filt))

```

PCA antes de normalizar 

```{r include=TRUE}
otu_table <- otu_table(physeq_agl_combined_t)
otu <- t(otu_table)
otu <- as.matrix(otu)

metadata <- sample_data(physeq_agl_combined_t)
meta <- as.matrix(metadata)
meta <- as.data.frame(meta)

cols <- c("project", "status")
meta[,cols] <- lapply(meta[,cols], as.factor)

pca_before <- pca(X = otu, ncomp = 2)

plot_pca_before <- PLSDAbatch::Scatter_Density(object = pca_before,
                                               batch = meta[,"project"],
                                               trt = meta[,"status"],
                                               batch.legend.title = 'Project',
                                               trt.legend.title = 'Status',
                                               title = 'Sin corrección',
                                               xlim = c(0, 12000), 
                                               ylim = c(-20000, 8000))
```

Normalización CLR 

```{r include=TRUE}
# CLR
datos_pseudo <- otu + 1
otu_clr <- logratio.transfo(as.matrix(datos_pseudo), logratio = 'CLR') 
View(otu_clr)

pca_before_clr <- pca(X = otu_clr, ncomp = 2)

plot_pca_before_clr <- PLSDAbatch::Scatter_Density(object = pca_before_clr,
                                               batch = meta[,"project"],
                                               trt = meta[,"status"],
                                               batch.legend.title = 'Project',
                                               trt.legend.title = 'Status',
                                               title = 'Sin corrección',
                                               xlim = c(-20, 20), 
                                               ylim = c(-20, 10))
```

Normalización ALR 

```{r include=TRUE}
# ALR 
alr_datos <- alr(datos_pseudo)
pca_before_alr <- pca(X = alr_datos, ncomp = 2)

plot_pca_before_alr <- PLSDAbatch::Scatter_Density(object = pca_before_alr,
                                               batch = meta[,"project"],
                                               trt = meta[,"status"],
                                               batch.legend.title = 'Project',
                                               trt.legend.title = 'Status',
                                               title = 'Sin corrección',
                                               xlim = c(-20, 20), 
                                               ylim = c(-20, 10))
```

Normalización por abundancias relativas 

```{r include=TRUE}
# Abundancia relativa 
otu_abr <- transform(otu, "compositional")

pca_before_abr <- pca(X = otu_abr, ncomp = 2)

plot_pca_before_abr <- PLSDAbatch::Scatter_Density(object = pca_before_abr,
                                               batch = meta[,"project"],
                                               trt = meta[,"status"],
                                               batch.legend.title = 'Project',
                                               trt.legend.title = 'Status',
                                               title = 'Sin corrección',
                                               xlim = c(-2500, 7000), 
                                               ylim = c(-5000, 5000))
```

```{r include=TRUE}
otu_table <- t(otu_clr)
sample_data <- sample_data(physeq_agl_combined_t)

# Especificar la carpeta donde se guardarán los archivos CSV
save_folder <- "C:/Users/Carla/Desktop/4o/Q1/TFG/samples"

# Guardar otu_table en un archivo CSV
write.csv(otu_table, file.path(save_folder, "otu_table_clr.csv"), row.names = TRUE)

# Guardar sample_data en un archivo CSV
write.csv(data.frame(sample_data), file.path(save_folder, "sample_data_clr.csv"), row.names = TRUE)
```
